### ISSUE TITLE
Configuration management

### ISSUE THREAD

**Issue by waltermoreira** [joestubbs/tagent#11]
# Managing configuration for tagent

There are already a few values that can be configured for `tagent`:
- root directory: we extract it from `TAGENT_HOME`, then current dir, then `HOME`
- pub key: we extract it from `TAGENT_PUB_KEY`, then fetch from `TAGENT_PUB_KEY_URL`
- ip and port

Should we think of a unified way to configure those values? I fear about needing more values in the future, and start spreading them into too many env vars.

I'd love to learn about what other tools for tapis use for configuration. Maybe a file and some defaults? Let's chat about this.

**Comment by joestubbs** [comment]
This is a great question. In Tapis, at least on the Python side, we use JSON together with JSONSchema to configure services. The idea is that the services provide a JSONSchema document specifying the configuration schema, and services are then started with a json config file that conforms to that schema (if it doesn't conform, the service doesn't start).

What I liked about JSONSchema was that it gives you a way of expressing the types for the configurations, at least to the extent that the JSON type system allows. For instance, it's nice to express that configuration value should be a JSON list or an object, instead of just some string. Here's the implementation, in case you're interested: https://github.com/tapis-project/tapipy-tapisservice/blob/main/tapisservice/config.py

I thought about using a system like this, but I did realize that the JSON types won't be enough to prevent us from needing error handling on the conversion to Rust types -- for instance, String to RsaPublicKey, String to Path, etc., but I will say it has been very nice in Python. 

For environment variables, there is the dotenv (https://crates.io/crates/dotenv) crate, which at least allows for specifying them in a file. We could also look at using ini files or something similar..

**Comment by waltermoreira** [comment]
While you take a stab at error handling, can I take a look at this and send some proposal?

**Comment by joestubbs** [comment]
of course!
