### ISSUE TITLE
Custom error handling

### ISSUE THREAD

**Issue by waltermoreira** [joestubbs/tagent#8]
Rework error handling to use the custom error.

**Comment by joestubbs** [comment]
Remove use of Either type in the handlers to use a Result with the custom error type

**Comment by waltermoreira** [comment]
Just so we don't forget, an example of using a custom error is in the branch: `error_handling`.

**Comment by joestubbs** [comment]
I thought this article was quite nice: https://blog.burntsushi.net/rust-error-handling/

It builds up from "first principles" a robust error handling mechanism, starting with panics, moving to combinators, and then custom error types that implement Error and From. I really enjoyed all of it (I only skimmed the case study), but you may want to skip to the summary since you are comfortable with combinators, etc.

But, I am wondering if we should take this same route of custom error types as enums of the possible error types they can encounter, and then implement the Error and From traits. Combined with the `?` operator, it seems to make for such nice code!

**Comment by waltermoreira** [comment]
Yes! That's pretty good. It's a long article, but skimming over it I get the conclusion is to implement `Error` and `From`, like you said. I really like the `From`, that was exactly what was missing, I think, in the RSAPubKey error that didn't let us use `?` in the test (and we needed to use the `unwrap()`).

**Comment by joestubbs** [comment]
Awesome! If you don't mind, I can take a shot at this one and see how it goes. I can do PR to get your thought on it..

**Comment by waltermoreira** [comment]
Of course! Look forward to the PR.

**Comment by waltermoreira** [comment]
We closed this issue, and I think we already have a very good way to manage the `TagentError` custom error.

I just saw these two crates that people say are becoming very standard, and thought to mention them for the future:
- [thiserror](https://github.com/dtolnay/thiserror): looks like just an easy way to do what we are currently doing, and
- [anyhow](https://github.com/dtolnay/anyhow): for the cases where one gives up a bit of control on the error in exchange for a very ergonomic `Result` type.

Not proposing to change things now, just bringing them up to your awareness.
